/*/****************************************************************************************************************************
// Erstellt 08.09.2015 von AM
//                         Klose und Srocke Gesellschaft für kreative Konfliktlösungen mbH
//                         Mindelweg 11
//                         22393 Hamburg 
//                         Tel.:  04064917161
//                         Fax.: 04064917162
//                         Email: kontakt@klosesrockepartner.de
//****************************************************************************************************************************
//
// Parameter: 
//
//****************************************************************************************************************************
//
// Beschreibung:
//                      
// erzeugt XML 
//
//
//****************************************************************************************************************************
//Änderungen:
// 27.11.2015 AM : Wenn LS.Lieferanschrift__c != null dann hat dieser Anschrift das höchste Priorität für createXML    
// 29.01.2016 von BT    Das Feld 'Geburtsdatum__c' wird durch das Feld 'Geburtsdatum_text__c' erstetzt      
// 19.02.2016 von BT    Einbau neues Element "OrderOptions"          
// 15.03.2016 AM : Partnername2 abh. von Art_der_anschrift             
//****************************************************************************************************************************
*/public with sharing class LS_XML_nachbearbeiten_batch {

    private list<Lieferschein__c> LSList = new list<Lieferschein__c>();
    private Map<ID, Anschrift__c> MapKdAnschr = new Map<ID, Anschrift__c> () ;
    private Map<ID, Anschrift__c> MapKdPdAnschr = new Map<ID, Anschrift__c> () ;
    private Map<ID, Anschrift__c> MapLsAnschr = new Map<ID, Anschrift__c> () ;
    private Map<ID, list<Lieferscheinposition__c>> MapLsLpos = new Map<ID, list<Lieferscheinposition__c>> () ;
    private CompanyInfo__c FirmenInfo {get; set;}
    private Organization orgDetails {get; set;}
    private Anschrift__c StandardLA ;
    private Lieferschein__c Lieferschein;
    private string kdnrBeiHartmann{get; set;}
    private map<ID, Lieferschein__c> updMapLS = new map<ID, Lieferschein__c>();
    public List<Attachment> attXMLlist2ins = new list<Attachment>();
    private set<ID> lsIdOhneXmlSet = new Set<ID>();
    private list<Lieferscheinposition__c> lpList = new list<Lieferscheinposition__c>();
    
    private map<id, string> kdAdNameMap = new map<id, string>();
    
    public LS_XML_generieren_batch genXML {get; set;}

    public LS_XML_nachbearbeiten_batch() {
    }

    public void setlsIdOhneXmlSet(set<id> lsIdOhneXmlSet) {
        this.lsIdOhneXmlSet = lsIdOhneXmlSet;
    }
    
    public void LS_XML_nachbearbeiten_los() {
        set<ID> lsIDSet = new Set<ID>();
        list<Lieferbest_tigung__c> lsidAllList = [SELECT Lieferschein__c FROM Lieferbest_tigung__c WHERE an_abena_versendet__c != true AND Lieferschein__c != null];
        if((lsidAllList != null) && (lsidAllList.size() > 0 )) {
            list<attachment> attXmlList = [Select ParentId 
                                            FROM Attachment 
                                            WHERE ParentId in (SELECT   Lieferschein__c FROM Lieferbest_tigung__c WHERE an_abena_versendet__c != true)
                                            LIMIT 10000];
            if((attXMLlist != null) && (attXMLlist.size() > 0) ) {
                for(attachment AT : attXMLlist) lsIDSet.add(AT.ParentId);
            }               
            
            
            
            
            for(Lieferbest_tigung__c LB : lsidAllList) {
                if(!lsIDSet.contains(LB.Lieferschein__c)) lsIdOhneXmlSet.add(LB.Lieferschein__c);
            }
            create_xml();
        }
    }



    public void create_xml()  {   
        if(!lsIdOhneXmlSet.isEmpty() ) {         

            Set<ID> KundeIDSet = new Set<ID>();
            Set<ID> LsOhneSet = new Set<ID>();
            map<id, id> lsAnMap = new map<id, id>();
            FirmenInfo = CompanyInfo__c.getValues('Default');
            kdnrBeiHartmann = FirmenInfo.KDNR_bei_Lieferant__c;  
            orgDetails = [SELECT Id, Name, Street, PostalCode, City, Country, State, Fax, Phone 
                            FROM Organization 
                            WHERE Id = :UserInfo.getOrganizationId()]; 
                            
            LSList = [SELECT id, Name, Kunde__c, Lieferschein_logik__c, Lieferschein_text__c, 
                            Kunde__r.Kundennummer_abena__c, Lieferdatum__c, Lieferanschrift__c,
                            Lieferanschrift__r.name,
                            Liefertext__c,
                            Kunde__r.Vorname__c, 
                            Kunde__r.Name__c,
                            Kunde__r.Lieferadresse__c,
                            Status_DHL__c,
                            Kunde__r.Kundennummer__c
                            FROM Lieferschein__c
                            WHERE id IN :lsIdOhneXmlSet];
            if((LSList != null) && (LSList.size() >0 )) {
                lpList = fillLposList();
                system.debug('####### lpList.size()=' + lpList.size());                                
                for(Lieferschein__c LS : LSList) {
                    KundeIDSet.add(LS.Kunde__c);    
                    // system.debug('####### checkLposList(LS.id)=' + checkLposList(LS.id));        
                    MapLsLpos.put(Ls.ID, checkLposList(LS.id));
                    if(LS.Lieferanschrift__c != null) {
                        lsAnMap.put(LS.Lieferanschrift__c, LS.id);
                    }                   
                }           
            }
            
            if(!lsAnMap.isEmpty()) {
            List<Anschrift__c> ListLsAn = [SELECT id, Name, Stra_e__c, PLZ__c, Ort__c, Hausnummer__c, Telefon__c, 
                        interne_Notiz__c, Liefernotiz__c, komb_Adresse__c, Kunde__c
                        FROM Anschrift__c WHERE id IN :lsAnMap.keySet()];   
                for(Anschrift__c AN : ListLsAn) {
                    MapLsAnschr.put(lsAnMap.get(AN.id), AN);
                }                           
            }           
            
            
            
            List<Anschrift__c> ListAn = [SELECT Name, Stra_e__c, PLZ__c, Ort__c, Hausnummer__c, Telefon__c, 
                        interne_Notiz__c, Liefernotiz__c, komb_Adresse__c, Kunde__c
                        FROM Anschrift__c WHERE Standardlieferanschrift__c = true AND Kunde__c IN :KundeIDset ];
            system.debug('#########################alex402 ListAn.size()=' + ListAn.size());                
            if (ListAn != null && ListAn.size() != 0) { 
                for (Anschrift__c LiAn : ListAn)
                    { 
                        MapKdAnschr.put(LiAn.Kunde__c, LiAn);
                    }
            }
            
            List<Anschrift__c> ListKundeAn = [SELECT Name, Kunde__c
                        FROM Anschrift__c WHERE Art_der_Anschrift__c = 'Kundenadresse'  
                        AND Kunde__c IN :KundeIDset ];              
            if (ListKundeAn != null && ListKundeAn.size() != 0) { 
                for (Anschrift__c LiKundeAn : ListKundeAn)
                    { 
                        kdAdNameMap.put(LiKundeAn.Kunde__c, LiKundeAn.name);
                    }
            }
            
            if((LSList != null) && (LSList.size() > 0)) {
                for(Lieferschein__c Ls : LSList) {
                    if(!createXML_PH(Ls)) {
                        updMapLS.put(Ls.id, LS);
                    }
                }
                if((attXMLlist2ins != null) && (attXMLlist2ins.size() > 0)) {
                    try {
                        // insert attXMLlist2ins;
                        Database.SaveResult[] sriCD = Database.insert(attXMLlist2ins, false);
                    }
                    catch(System.Exception e) {
                        system.debug('#########################alex800 Fehler insert XML e='  + e);
                    }
                }
            }
        }
    }

    private boolean createXML_PH(Lieferschein__c Ls) {
        boolean error = false;
        
        if(LS.Kunde__r.Vorname__c == null) LS.Kunde__r.Vorname__c = ' ';
        if(LS.Kunde__r.Name__c == null) LS.Kunde__r.Name__c = ' ';  
        
        try {
        Anschrift__c LiAn = MapKdAnschr.get(ls.Kunde__c);  
        Anschrift__c PdAnschr = new Anschrift__c();
        
        if(MapLsAnschr.containsKey(Ls.id)) {
            PdAnschr = MapLsAnschr.get(Ls.id);
        }
        else {              
            PdAnschr = LiAn;
        }

        
        integer posNo = 1;
        string docName = null;
        Datetime curDate = Datetime.now();
        Datetime delDate = Datetime.now();
        if(Ls.Lieferdatum__c != null) {         
            delDate = datetime.newInstance(Ls.Lieferdatum__c, Time.newInstance(0, 0, 0, 0));
        }  
        string lieferdatum = delDate.format('YYYYMMdd');
        string datumHeute = curDate.format('YYYYMMdd');
        string zeitJetzt = curDate.format('HHmmss');
        list<Lieferscheinposition__c> lpl = MapLsLpos.get(Ls.ID);

        // 26.05.2016 Prüfen Lpos 
        if((lpl != null) && (lpl.size() > 0)) {
            list<Lieferscheinposition__c> lpc = new list<Lieferscheinposition__c>();
            for(Lieferscheinposition__c LP : lpl) {
                if(LP.Lieferschein__c == Ls.ID) lpc.add(LP);                
            }
            if((lpc != null) && (lpc.size() > 0)) {
                lpl.clear();
                lpl.addAll(lpc);
            } else return true;
            
        } else return true;        
        
        Xmlstreamwriter xmlW = new Xmlstreamwriter();
        xmlW.writeStartDocument('utf-8','1.0');
            xmlW.writeStartElement(null,'PHOrders', null);
            xmlW.writeAttribute(null,null,'xmlns:xsi','http://www.w3.org/2001/XMLSchema-instance');
            docName = Ls.Name + '.XML';
            
            // PHTransfer
            xmlW.writeStartElement(null,'PHTransfer', null);
                xmlW.writeStartElement(null,'SenderID', null);
                    xmlW.writeCharacters(kdnrBeiHartmann);
                xmlW.writeEndElement();               
                xmlW.writeStartElement(null,'ReceiverID', null);
                    xmlW.writeCharacters('4049500000000');
                xmlW.writeEndElement();             
                xmlW.writeStartElement(null,'Date', null);
                    xmlW.writeCharacters(datumHeute);
                xmlW.writeEndElement();     
                xmlW.writeStartElement(null,'Time', null);
                    xmlW.writeCharacters(zeitJetzt);
                xmlW.writeEndElement(); 
                xmlW.writeStartElement(null,'VersionID', null);
                    xmlW.writeCharacters('1.8.3');
                xmlW.writeEndElement();                 
            xmlW.writeEndElement();
            // PHTransfer
            
            xmlW.writeStartElement(null,'Order', null);
            xmlW.writeAttribute(null,null,'type','TA');
            // 
                xmlW.writeStartElement(null,'OrderHeader', null);
                    xmlW.writeStartElement(null,'ReferencedOrder', null);
                        xmlW.writeStartElement(null,'BuyerOrderNumber', null);
                            xmlW.writeCharacters(Ls.Name + ' - ' + Ls.Kunde__r.Kundennummer_abena__c);
                        xmlW.writeEndElement();
                        xmlW.writeStartElement(null,'Date', null);
                            xmlW.writeCharacters(lieferdatum);
                        xmlW.writeEndElement();
                        xmlW.writeStartElement(null,'ReferenceID', null);
                            xmlW.writeCharacters(Ls.Name);
                        xmlW.writeEndElement();             
                    //ReferencedOrder 
                    xmlW.writeEndElement(); 
                    
                    xmlW.writeStartElement(null,'BuyerParty', null);
                        xmlW.writeStartElement(null,'PartnerID', null);
                        xmlW.writeAttribute(null,null,'type','Distributor');
                            xmlW.writeCharacters(kdnrBeiHartmann);
                        xmlW.writeEndElement();
                        xmlW.writeStartElement(null,'PartnerName1', null);
                            xmlW.writeCharacters(orgDetails.Name);
                        xmlW.writeEndElement(); 
                        xmlW.writeStartElement(null,'PartnerAddress', null);
                            xmlW.writeCharacters(orgDetails.Street );
                        xmlW.writeEndElement();  
                        xmlW.writeStartElement(null,'PartnerPostalCode', null);
                            xmlW.writeCharacters(orgDetails.PostalCode);
                        xmlW.writeEndElement();                         
                        xmlW.writeStartElement(null,'PartnerCity', null);
                            xmlW.writeCharacters(orgDetails.City );
                        xmlW.writeEndElement();     
                        xmlW.writeStartElement(null,'PartnerCountryCode', null);
                            xmlW.writeCharacters('DE');
                        xmlW.writeEndElement();                         
                        xmlW.writeStartElement(null,'PartnerPhone', null);
                            xmlW.writeCharacters(FirmenInfo.Telefon__c);
                        xmlW.writeEndElement(); 
                        xmlW.writeStartElement(null,'PartnerFax', null);
                            xmlW.writeCharacters(FirmenInfo.Fax__c);
                        xmlW.writeEndElement();                         
                    // BuyerParty
                    xmlW.writeEndElement();                 
                    
                    xmlW.writeStartElement(null,'DestinationParty', null);
                        xmlW.writeStartElement(null,'PartnerID', null);
                        xmlW.writeAttribute(null,null,'type','Distributor');
                            // xmlW.writeCharacters(LS.Kunde__r.Kundennummer_abena__c);
                            xmlW.writeCharacters('99999951');
                        xmlW.writeEndElement(); 
                        xmlW.writeStartElement(null,'PartnerReferenceID', null);
                        xmlW.writeAttribute(null,null,'type','Customer');
                            xmlW.writeCharacters(string.valueOf(integer.valueOf(LS.Kunde__r.Kundennummer__c)));
                        xmlW.writeEndElement(); 
                        xmlW.writeStartElement(null,'PartnerName1', null);
                            xmlW.writeCharacters(PdAnschr.Name);
                        xmlW.writeEndElement(); 
                        
                        // if(LS.Kunde__r.Vorname__c != null) {
                            // if((!PdAnschr.Name.contains(LS.Kunde__r.Name__c)) && (!PdAnschr.Name.contains(LS.Kunde__r.Vorname__c))) {
                                // xmlW.writeStartElement(null,'PartnerName2', null);
                                    // xmlW.writeCharacters(LS.Kunde__r.Vorname__c + ' ' + LS.Kunde__r.Name__c );
                                // xmlW.writeEndElement(); 
                            // }                           
                        // }
                        // else {
                            // if(!PdAnschr.Name.contains(LS.Kunde__r.Name__c))  {
                                // xmlW.writeStartElement(null,'PartnerName2', null);
                                    // xmlW.writeCharacters(LS.Kunde__r.Name__c );
                                // xmlW.writeEndElement(); 
                            // }                               
                        // }

                        if(kdAdNameMap.containsKey(LS.Kunde__c)) {
                            if(LS.Lieferanschrift__r.name != kdAdNameMap.get(LS.Kunde__c))  {
                                xmlW.writeStartElement(null,'PartnerName2', null);
                                    xmlW.writeCharacters(LS.Kunde__r.Vorname__c + ' ' + LS.Kunde__r.Name__c );
                                xmlW.writeEndElement(); 
                            }
                        }

                        
                        xmlW.writeStartElement(null,'PartnerAddress', null);
                            xmlW.writeCharacters(PdAnschr.Stra_e__c );
                        xmlW.writeEndElement();     
                        xmlW.writeStartElement(null,'PartnerPostalCode', null);
                            xmlW.writeCharacters(PdAnschr.PLZ__c);
                        xmlW.writeEndElement();     
                        xmlW.writeStartElement(null,'PartnerCity', null);
                            xmlW.writeCharacters(PdAnschr.Ort__c );
                        xmlW.writeEndElement(); 
                        xmlW.writeStartElement(null,'PartnerCountryCode', null);
                            xmlW.writeCharacters('DE');
                        xmlW.writeEndElement();                                                 
                    // DestinationParty
                    xmlW.writeEndElement();
                    
                    xmlW.writeStartElement(null,'SellerParty', null);
                        xmlW.writeStartElement(null,'PartnerID', null);
                        xmlW.writeAttribute(null,null,'type','EAN');
                            xmlW.writeCharacters('4049500000000');
                        xmlW.writeEndElement();
                        xmlW.writeStartElement(null,'PartnerName1', null);
                            xmlW.writeCharacters('Paul Hartmann AG');
                        xmlW.writeEndElement();             
                        //SellerParty
                    xmlW.writeEndElement();
                    // OrderOptions  
                    if(Ls.Liefertext__c == 'Shop') {
                        xmlW.writeStartElement(null,'OrderOptions', null);
                          xmlW.writeStartElement(null,'Preisgruppe', null);
                          xmlW.writeCharacters('M');
                         xmlW.writeEndElement(); 
                        xmlW.writeEndElement();  
                    }                                      
                // OrderHeader 
                xmlW.writeEndElement(); 
                
                xmlW.writeStartElement(null,'OrderLines', null);
                for(Lieferscheinposition__c lp : lpl) {
                    xmlW.writeStartElement(null,'OrderLine', null);
                        xmlW.writeStartElement(null,'LineNumber', null);
                        xmlW.writeAttribute(null,null,'type','TA');
                            xmlW.writeCharacters(string.valueOf(posNo));
                        xmlW.writeEndElement();
                        xmlW.writeStartElement(null,'ProductNumber', null);
                        xmlW.writeAttribute(null,null,'type','EAN');
                        if(lp.Artikel__r.a_pac_apo_EAN_UPC__c != null) {
                            xmlW.writeCharacters(string.valueOf(lp.Artikel__r.a_pac_apo_EAN_UPC__c));
                        }
                        else {
                            xmlW.writeCharacters('hier EAN');
                        }
                        xmlW.writeEndElement();
                        xmlW.writeStartElement(null,'Quantity', null);
                            xmlW.writeCharacters(string.valueOf(lp.Menge__c));
                        xmlW.writeEndElement();             
                        // OrderLine
                    xmlW.writeEndElement(); 
                    posNo++;
                }                                   
                // OrderLines
                xmlW.writeEndElement();
                
            // Order
            xmlW.writeEndElement();
            // =============================================
        // PHXOrders    
        xmlW.writeEndElement(); 
        xmlW.writeEndDocument();
        string xmlString = xmlW.getXmlString();
        System.debug('###################The XML :'+xmlString); 
        xmlW.close();
        
        Attachment attachment = new Attachment();
        attachment.Body = blob.valueOf(xmlString);
        attachment.Name = docName;
        attachment.ParentId = Ls.ID;
        // insert attachment;
        attXMLlist2ins.add(attachment);
        }
        catch (System.Exception e) {
            error = true;
            System.debug('###################create XML error :'+e); 
                        
        }
        return error;
    }
    
    public list<Lieferscheinposition__c> fillList(id lsid) {
        List<Lieferscheinposition__c> LSbed = [SELECT 
                        l.Status__c, l.Name, l.Id, 
                        l.Menge__c, l.VZ_bis__c, l.VZ_von__c,
                        l.Lieferdatum__c, 
                        l.Lieferschein__c,
                        l.Lieferschein__r.Name, 
                        l.Lieferschein__r.Lieferdatum__c, 
 
                        l.Artikel__r.Name, 
                        l.Artikel__r.PZN__c,
                        l.Artikel__r.a_pac_apo_Langname__c,
                        l.Artikel__r.Artikelnummer_des_Herstellers__c,
                        l.Artikel__r.Anlage_4_Preis__c,
                        l.Artikel__r.EVK__c,  
                        l.Artikel__r.v_pos_1_Name__c,
                        l.Artikel__r.Einheit__c,
                        l.Artikel__r.a_pac_apo_EAN_UPC__c,
                         
                        l.Kunde__c, 
                        l.Kunde__r.Name,                    
                        l.Kunde__r.Pflegedienst__r.Name,
                        l.Kunde__r.Pflegedienst__r.Abena_Sammellieferung__c,
                        l.Kunde__r.Krankenkasse__r.Name, 
                        l.Kunde__r.Liefermodus__c, 
                        l.Kunde__r.Art_der_Bestellung__c,
                        l.Kunde__r.Vorname__c, 
                        l.Kunde__r.Name__c, 
                        l.Kunde__r.Kundennummer_abena__c, 
                        l.Kunde__r.Versichertennummer__c, 
                        l.Kunde__r.Ort__c,
                        l.Kunde__r.PLZ__c,
                        l.Kunde__r.Stra_e__c,
                        l.Kunde__r.Geburtsdatum_text__c,  
                        l.Kunde__r.Material_Einmalhandschuhe__c,
                        l.Kunde__r.Gr_e_Einmalhandschuhe__c,
                        
                        l.Auftragsposition__c,
                        l.Auftragsposition__r.Name, 
                        l.Auftragsposition__r.Restmenge__c, 
                        l.Auftragsposition__r.Gen_Menge_Stk_Mon__c, 
                        l.Auftragsposition__r.Gen_Menge_ges__c,
                        l.Auftragsposition__r.genehmigt_bis__c, 
                        l.Auftragsposition__r.Lieferzeitraum__c,
                        l.Auftragsposition__r.Preis__c,
                        l.Auftragsposition__r.Positionsart__c,

                        l.Auftragsposition__r.Auftrag__r.Bezeichnung__c
                        
                    FROM Lieferscheinposition__c l
                    WHERE l.Lieferschein__c = :lsid
                    ];  
        return LSbed;       
    }
    
    public list<Lieferscheinposition__c> fillLposList() {
        List<Lieferscheinposition__c> LSbed = [SELECT 
                        l.Status__c, l.Name, l.Id, 
                        l.Menge__c, l.VZ_bis__c, l.VZ_von__c,
                        l.Lieferdatum__c, 
                        l.Lieferschein__c,
                        l.Lieferschein__r.Name, 
                        l.Lieferschein__r.Lieferdatum__c, 
 
                        l.Artikel__r.Name, 
                        l.Artikel__r.PZN__c,
                        l.Artikel__r.a_pac_apo_Langname__c,
                        l.Artikel__r.Artikelnummer_des_Herstellers__c,
                        l.Artikel__r.Anlage_4_Preis__c,
                        l.Artikel__r.EVK__c,  
                        l.Artikel__r.v_pos_1_Name__c,
                        l.Artikel__r.Einheit__c,
                        l.Artikel__r.a_pac_apo_EAN_UPC__c,
                         
                        l.Kunde__c, 
                        l.Kunde__r.Name,                    
                        l.Kunde__r.Pflegedienst__r.Name,
                        l.Kunde__r.Pflegedienst__r.Abena_Sammellieferung__c,
                        l.Kunde__r.Krankenkasse__r.Name, 
                        l.Kunde__r.Liefermodus__c, 
                        l.Kunde__r.Art_der_Bestellung__c,
                        l.Kunde__r.Vorname__c, 
                        l.Kunde__r.Name__c, 
                        l.Kunde__r.Kundennummer_abena__c, 
                        l.Kunde__r.Versichertennummer__c, 
                        l.Kunde__r.Ort__c,
                        l.Kunde__r.PLZ__c,
                        l.Kunde__r.Stra_e__c,
                        l.Kunde__r.Geburtsdatum_text__c,  
                        l.Kunde__r.Material_Einmalhandschuhe__c,
                        l.Kunde__r.Gr_e_Einmalhandschuhe__c,
                        
                        l.Auftragsposition__c,
                        l.Auftragsposition__r.Name, 
                        l.Auftragsposition__r.Restmenge__c, 
                        l.Auftragsposition__r.Gen_Menge_Stk_Mon__c, 
                        l.Auftragsposition__r.Gen_Menge_ges__c,
                        l.Auftragsposition__r.genehmigt_bis__c, 
                        l.Auftragsposition__r.Lieferzeitraum__c,
                        l.Auftragsposition__r.Preis__c,
                        l.Auftragsposition__r.Positionsart__c,

                        l.Auftragsposition__r.Auftrag__r.Bezeichnung__c
                        
                    FROM Lieferscheinposition__c l
                    WHERE l.Lieferschein__c IN :lsIdOhneXmlSet
                    ];  
        return LSbed;       
    }   

    public list<Lieferscheinposition__c> checkLposList(ID LsID) {
        List<Lieferscheinposition__c> LSbed = new list<Lieferscheinposition__c>();
        for (Lieferscheinposition__c LP : lpList) {
            if(LP.Lieferschein__c == LsID) LSbed.add(LP);
        }
        
        
        return LSbed; 
    }
    
        // wird nicht aufgerufen! Nur für Testabdeckung!!!  
        public class dummyZeile {
                
                        public String Rpos {get;set;}
                        public String Anzahl_Verpackungen {get;set;}
                        public String LsNr {get;set;}
                        public String Positionsnummer_PZN {get;set;}
                        public String Artikel {get;set;}
                        public String Menge {get;set;}
                        public String Me2 {get;set;}
                        public string ME {get;set;}
                        public string Brutto {get;set;}
                        public string seitenw {get;set;}
                        public string th {get; set;}
                        public string thu {get; set;}
                        public string trs {get; set;}
                        public string lDatum {get; set;}
                        public string stern {get; set;}
        }

// wird nicht aufgerufen! Nur für Testabdeckung!!!       
        public void setLeereZeilen() {
            List<dummyZeile> pZeilen = new List<dummyZeile>();
            dummyZeile dZeile = new dummyZeile();
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);   
                            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);   
                            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);   
                            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);   
                            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);   
                            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);          
            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
                    
            dZeile.Rpos = '. 2';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '2';  
            dZeile.stern = '2';  
            pZeilen.add(dZeile);   
               
            dZeile.Rpos = '. 3';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '3';  
            dZeile.stern = '4';  
            pZeilen.add(dZeile);      

            dZeile.Rpos = '. 4';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '13';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 31';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '31';  
            dZeile.stern = '31';  
            pZeilen.add(dZeile);      
            
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '41';  
            dZeile.stern = '41';  
            
            pZeilen.add(dZeile);      
            dZeile.Rpos = '. 41';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '51';  
            dZeile.stern = '61';  
            pZeilen.add(dZeile);   
                            
            dZeile.Rpos = '. 1';
            dZeile.Anzahl_Verpackungen = '. ';
            dZeile.th = 'color:white;border:0px;';
            dZeile.thu = 'color:white;border:0px;';
            dZeile.lDatum = '1';  
            dZeile.stern = '1';  
            pZeilen.add(dZeile);  
            
        }
    
}