@isTest
private class magento_test {
    static testMethod void myUnitTest() {
        new magento.filters();
        new magento.associativeArray();
        new magento.complexFilterArray();
        new magento.complexFilter();
        new magento.associativeEntity();
        new magento.salesOrderItemEntityArray();
        new magento.salesOrderItemEntity();
        new magento.salesOrderListRequestParam_element();
        new magento.salesOrderListResponseParam_element();
        new magento.salesOrderListEntityArray();
        new magento.salesOrderListEntity();
        new magento.loginParam_element();
        new magento.loginResponseParam_element();
        new magento.salesOrderInfoRequestParam_element();
        new magento.salesOrderInfoResponseParam_element();
        new magento.salesOrderEntity();
        new magento.salesOrderAddressEntity();
        new magento.salesOrderPaymentEntity();
        new magento.salesOrderStatusHistoryEntityArray();
        new magento.salesOrderStatusHistoryEntity();
        magento.port mp = new magento.port();
    }   
}