public class SF_MC_Statics {
	// keys for mapping
	public static string SFIDKEY = 'sfID';
	public static string OPTINKEY = 'OM_Opt_In__c';
	public static string TIMESTAMPKEY = 'optin_timestamp';
	// error messages
	public static string NOINDIVIDUALFOUNDERROR = 'no individual found to update';
	public static string INDIVUDUALUPDATEERROR = 'failed to update individuals. err: ';
	public static string NOOBJECTFOUNDERROR = 'could not find any lead or contact with id: ';
	public static string NOINDIVIDUALFOUNDONLEAD = 'could not find any Individual on Lead with id: ';
	public static string NOINDIVIDUALFOUNDONCONTACT = 'could not find any Individual on Contact with id: ';
}